/*
 * 3D Model Thumbnail Service
 *
 * Service for generating thumbnails from 3D models
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using thumbnailService.Attributes;
using thumbnailService.Models;

namespace thumbnailService.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Checking service is online and responsive.</remarks>
        /// <response code="200">Ping response</response>
        [HttpGet]
        [Route("/ping")]
        [ValidateModelState]
        [SwaggerOperation("PingGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Ping response")]
        public abstract IActionResult PingGet();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelID">The Guid of the model to retrieve</param>
        /// <param name="inlineObject"></param>
        /// <response code="200">Returns the thumbnail of the posted model.</response>
        [HttpPost]
        [Route("/submitModel")]
        [Consumes("multi/form-data")]
        [ValidateModelState]
        [SwaggerOperation("SubmitModelPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(IconResponse), description: "Returns the thumbnail of the posted model.")]
        public abstract IActionResult SubmitModelPost([FromQuery (Name = "modelID")][Required()]Guid modelID, [FromBody]InlineObject inlineObject);
    }
}
