version: "3.9"
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - .postgres/initTables.sql:/docker-entrypoint-initdb.d/initTables.sql
   #   - .postgresql/1-initData.sql:/docker-entrypoint-initdb.d/1-initData.sql
    env_file:
      - psql/.env.database
    
