version: "3.9"
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - psql/.env.database
    
